default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: salad_days_development

test:
  <<: *default
  database: salad_days_test


production:
  <<: *default
  database: salad_days_production
  username: postgres
  password: <%= ENV['SALAD_DAYS_DATABASE_PASSWORD'] %>

