default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: salad_days_development

test:
  <<: *default
  database: salad_days_test


production:
  <<: *default
  database: salad_days_production
  username: salad_days
  password: <%= ENV['SALAD_DAYS_DATABASE_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: salad_days_development
  host: localhost
  pool: 5
  username: deployment
  password: horsetooth

test:
  adapter: postgresql
  encoding: unicode
  database: salad_days_test
  host: localhost
  pool: 5
  username: deployment
  password: horsetooth

production:
  adapter: postgresql
  encoding: unicode
  database: salad_days
  host: localhost
  pool: 5
  username: deployment
  password: horsetooth
